### ISSUE TITLE
[Parsing error] "require" is not fully supported

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#10]
The following piece of code does not parse:

```
class ssh () {
  require abc
}
```

**Comment by iwarapter** [comment]
See https://docs.puppetlabs.com/puppet/latest/reference/lang_relationships.html#syntax-the-require-function

Missing support for the require function statement.

**Comment by iwarapter** [comment]
For specific syntax requirements.

See https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#using-require

**Comment by iwarapter** [comment]
Going to go out on a limb and say https://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#using-contain also isnt supported...

**Comment by iwarapter** [comment]
Hi David,

Do you want to give the new changes a go?

**Comment by racodond** [comment]
Down from 243 to 124 parsing errors. Good job!
I'll check the remaining parsing errors tomorrow. Time to go to bed, here, in France :-)

**Comment by iwarapter** [comment]
Yeah it's 1:30am here in the UK gonna finish the multiple resource bodies and pick up tomorrow evening.

Thanks for your help, much appreciated!

**Comment by racodond** [comment]
Fixed!
