### ISSUE TITLE
Renaming packages com.iadams.sonarqube.xxx into org.sonarqube.xxx

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#102]
@iwarapter : Is that OK with you?

**Comment by iwarapter** [comment]
@racodond i'd only do this if the project moved into the sonar community group, as this is currently a 3rd party plugin i don't think we should do this.

**Comment by racodond** [comment]
OK

**Comment by iwarapter** [comment]
Might be worth seeing if they are interested in this become part of the community plugin set. I think we should get the next release out and get some wider community feedback then see if there is interest.

**Comment by racodond** [comment]
Yep, we're almost ready for the "1.0" release. Also, I'll try and talk to the Puppet Labs guys when they come visit us at the company I'm currently working for. I'll see if they can endorse it, promote it, provide feedback and if we can work together to provide even more value.
