### ISSUE TITLE
[Parsing error] Selectors are not fully supported

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#11]
The following piece of code does not parse (selector with default value only)

```
$vdir_mode = $env_type ? {
  default => '0755'
}
```

The following piece of code does not parse but should:

```
$toto = $titi ? {
  24 => 'abc',
}
```

See https://docs.puppetlabs.com/puppet/latest/reference/lang_conditional.html#case-matching-1

Also, the following piece of code is not properly parsed:

```
$root_group = $id ? {
 root    => 0,
}
```

**Comment by iwarapter** [comment]
Hi David,

The grammar is setup to match the defined syntax:
https://docs.puppetlabs.com/puppet/latest/reference/lang_conditional.html#syntax-3

As such it read this part as the selector statement:

```
$env_type ? {
  'dev'   => '0757',
  default => '0755'
}
```

The full expression you gave is then classed as an assignment (of the evaluated selector statement).

Is this not what you would expect?

**Comment by racodond** [comment]
My bad! My analysis of the parsing error wasn't thorough enough. Selectors are supported but not when there's only the default value. I updated the description of the issue accordingly.

**Comment by iwarapter** [comment]
@racodond This should now work as expected, can you confirm?

**Comment by racodond** [comment]
I confirm.
