### ISSUE TITLE
Replace Pplint:autoloader_layout

### ISSUE THREAD

**Issue by iwarapter** [iwarapter/sonar-puppet#112]
https://docs.puppetlabs.com/guides/style_guide.html#separate-files
http://puppet-lint.com/checks/autoloader_layout/

**Comment by iwarapter** [comment]
@racodond Care to take a look.

**Comment by racodond** [comment]
Nice job!

PR: https://github.com/iwarapter/sonar-puppet/pull/119 and my review: https://github.com/iwarapter/sonar-puppet/commit/801b5ee280ea343e71a459868d4d49b94349fcee

You can also directly create the PR when you want me to review
