### ISSUE TITLE
ResourcePasswordSet and UserResourceLiteralName should cover the 3 types of resource

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#118]

**Comment by iwarapter** [comment]
@racodond The UserResourceLiteralName doesn't need to support resource default or resource override.

I have extended the UserResourcePasswordNotSetCheck to cover the 3 types resource and the rule now follows similar implementations for doing this.

**Comment by racodond** [comment]
> @racodond The UserResourceLiteralName doesn't need to support resource default or resource override.

Indeed

> I have extended the UserResourcePasswordNotSetCheck to cover the 3 types resource and the rule now follows similar implementations for doing this.

PR created and merged: https://github.com/iwarapter/sonar-puppet/pull/120
