### ISSUE TITLE
[Parsing error] Parentheses not required for statement functions

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#13]
The following piece of code is properly parsed as expected:

```
fail('hello')
```

The following piece of code does not parse but should:

```
fail 'hello'
```

The only real difference between statement functions and other functions is that you can omit parentheses when calling a statement function with at least one argument... See https://docs.puppetlabs.com/puppet/latest/reference/lang_functions.html

**Comment by iwarapter** [comment]
@racodond This should now work as expected, can you confirm?

**Comment by racodond** [comment]
@iwarapter: If we really want to match the Puppet syntax, parenthesis are only optional for statement functions. I will create another issue but it is really minor. Also, I will create an issue to add a rule enforcing parentheses in function calls.
