### ISSUE TITLE
[Lexer error] Float cannot be lexed

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#135]
`0.3` => OK
`1.3` => KO

See https://github.com/iwarapter/sonar-puppet/commit/fcd75e734574cc0471fea971e2af46b39ef9109e

**Comment by iwarapter** [comment]
This is ordering again however needs to be carefully handled, essentially its currently finding and INTEGER(1) first instead of a FLOAT(1.3) the regex need to be rewritten to be more restrictive to mark a float as only a number with a single dot `[0-9]*\.[0-9]+` maybe?

**Comment by racodond** [comment]
According to https://docs.puppetlabs.com/puppet/latest/reference/lang_data_number.html#floating-point-numbers and https://github.com/puppetlabs/puppet/blob/3.x/lib/puppet/parser/lexer.rb#L210, the regular expression for a float would be something like:

```
-?\d+\.\d+([eE]-?\d+)?
```

**Comment by iwarapter** [comment]
The main problem is the lexer ordering: 

```
.withChannel(regexp(PuppetTokenType.HEX_INTEGER, "0(x|X)[0-9a-fA-F]+"))
.withChannel(regexp(PuppetTokenType.OCTAL_INTEGER, "0[0-7]+"))
.withChannel(regexp(PuppetTokenType.INTEGER, "[1-9][0-9]*"))
.withChannel(regexp(PuppetTokenType.FLOAT, "0?\\d+(\\.\\d+)?([eE]-?\\d+)?"))
```

As in the case with 1.3 it read it as INTEGER DOT INTEGER instead of FLOAT, i'll put together a healthy suite of tests for the lexer when i get home and can make sure i nail this down.
