### ISSUE TITLE
[Parse error] Hash array access and selectors in resource title are not supported

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#137]
The following pieces of code cannot be parsed:

```
file { $::value[2]:
  content => template('wms3/rfclient_bashprofile_custom.erb'),
}
```

```
file { $rootgroup = $osfamily ? {
          'Solaris'          => 'wheel',
          default            => 'root' }:
  content => template('wms3/rfclient_bashprofile_custom.erb'),
}
```

**Comment by iwarapter** [comment]
I just looked at the resource_name grammar, https://github.com/iwarapter/sonar-puppet/blob/master/puppet-squid/src/main/java/com/iadams/sonarqube/puppet/api/PuppetGrammar.java#L222 i suspect because variable is before hash_array_access then its reading this as:
NAME LBRACK VARIABLE ARRAY instead of NAME LBRACK HASH_ARRAY_ACCESS ....

**Comment by racodond** [comment]
Exactly. I'm currently fixing it.

**Comment by iwarapter** [comment]
Just bump it ahead in the list, it should ideally try to solve all the complex cases first selectors etc.

**Comment by racodond** [comment]
Hash array access fixed (https://github.com/iwarapter/sonar-puppet/commit/d77aadcf48f90078798d13bc5663d9a26e38b821) but not selectors.
Opened branch: https://github.com/iwarapter/sonar-puppet/tree/Issue_137_hash_array_access_and_selector_as_resource_name_cannot_be_parsed

**Comment by iwarapter** [comment]
```
[vagrant@localhost puppet_examples]$ puppet parser validate selector_resource_name.pp 
Error: Could not parse for environment production: Syntax error at '='; expected '}' at /home/vagrant/puppet_examples/selector_resource_name.pp:1
[vagrant@localhost puppet_examples]$ cat selector_resource_name.pp 
file { $rootgroup = $osfamily ? {
          'Solaris'          => 'wheel',
          default            => 'root' }:
  content => template('wms3/rfclient_bashprofile_custom.erb'),
}
[vagrant@localhost puppet_examples]$ puppet parser validate selector_resource_name.pp 
Error: Could not parse for environment production: Syntax error at '='; expected '}' at /home/vagrant/puppet_examples/selector_resource_name.pp:1
[vagrant@localhost puppet_examples]$ vi selector_resource_name.pp
[vagrant@localhost puppet_examples]$ cat selector_resource_name.pp 
file { $osfamily ? {
          'Solaris'          => 'wheel',
          default            => 'root' }:
  content => template('wms3/rfclient_bashprofile_custom.erb'),
}
[vagrant@localhost puppet_examples]$ puppet parser validate selector_resource_name.pp 
[vagrant@localhost puppet_examples]$ 
```

@racodond the selector example you pasted above doesnt validate as its an assignment, however if i remove the assignment and leave just the selector it does validate (and parse in the plugin)

**Comment by racodond** [comment]
My bad! On issue fixed then :-)
