### ISSUE TITLE
[Parse errors] With bare words

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#140]
Should the following pieces of code be valid? It looks like they are accepted by the Puppet compiler.

```
if $ensure == present {}
```

```
if(haproxy_clustername == undef) {}
```

```
case $::lsbmajdistrelease {
   5, 6: {
      $os_rel = $::lsbmajdistrelease
   }
   default: {
     $os_rel = 6
   }
}
```

```
$director_node  = wms3::director_node
```

**Comment by racodond** [comment]
Everything is fixed but now

```
  $director_node         = wms3::director_node
  Class['wms3::users'] -> Class['wms3::fs']
```

cannot be parsed.

**Comment by iwarapter** [comment]
I put both lines in the sslr toolkit and they parse (individually)

**Comment by racodond** [comment]
Yep they parse individually but not together.

**Comment by iwarapter** [comment]
@racodond I think this relates to #148 as i suspect the assignment is expecting something after it to form a larger expression, i'll refactor the expression definition to remove assignment and i suspect that will solve this.

**Comment by iwarapter** [comment]
Hmm interestingly this also doesn't parse:

```
  $director_node         = wms3::director_node
  $director_node         = wms3::director_node
```

So definitely think its the way the assignment grammar is working.

**Comment by racodond** [comment]
Nice
