### ISSUE TITLE
[Parse error] Case control expression should accept any expression resolving to a value

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#141]
See https://docs.puppetlabs.com/puppet/3.8/reference/lang_conditional.html#syntax-2. Thus the following piece of code should be properly parsed:

```
case $osver[0] {
 default: { }
}
```

**Comment by iwarapter** [comment]
The case statements where not something i covered in the recent major grammar rework unfortunately, i'll refactor this now.
