### ISSUE TITLE
[Parsing error] Last attribute and value pair can end with a semicolon

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#15]
I'm having a hard time finding a reference that states that the following syntax is valid:

```
class {'jenkins::package' :
  version => $version;  /* <-- ending with a semicolon */
}
```

but our code seems to be properly parsed.
I found this: https://books.google.fr/books?id=wEInCgAAQBAJ&pg=PA45&dq=Each+attribute+and+value+pair+should+end+with+a+comma.+The+last+attribute+should+end+in+a+comma+or+a+semicolon&hl=fr&sa=X&ved=0CCEQ6AEwAGoVChMImNqHgOTlxgIVCVwUCh2vrgoG#v=onepage&q=Each%20attribute%20and%20value%20pair%20should%20end%20with%20a%20comma.%20The%20last%20attribute%20should%20end%20in%20a%20comma%20or%20a%20semicolon&f=false

This is very minor. So, no need to cover this case if it is too complex.
If we manage to cover this case, we should add a rule preventing such construct.

**Comment by iwarapter** [comment]
@racodond should be fixed can you confirm?

**Comment by racodond** [comment]
Fixed!
