### ISSUE TITLE
[Parsing error] Array sectioning doesn't seem to be supported

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#16]
See https://docs.puppetlabs.com/puppet/latest/reference/lang_data_array.html#array-sectioning

**Comment by iwarapter** [comment]
@racodond can you check this resolves your issues please.

**Comment by racodond** [comment]
Not fully supported yet.
@iwarapter: I'll let you review PR https://github.com/iwarapter/sonar-puppet/pull/49.

**Comment by iwarapter** [comment]
PR Merged.
