### ISSUE TITLE
Add check: Classes and defines should not be too complex

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#162]
We first need to define what increases the complexity: if, selector, case, resource, resource override, resource default, ...

**Comment by iwarapter** [comment]
If were looking at in terms of cyclomatic complexity then its any conditional, im going to add a metrics label so we can track all these types of issues.

**Comment by racodond** [comment]
> If were looking at in terms of cyclomatic complexity then its any conditional

I believe that we should increase the complexity for resources as well. Indeed a class defining a thousand resources should be more complex than a class defining only 10 resources. We have to come up with our own valuable definition of complexity for Puppet.

In Java, for example, they increase the complexity of a class  for each method/function. And we mapped resources to functions, so we should mimic Java and increase the complexity for each function (=resource).

**Comment by iwarapter** [comment]
OK, i didnt realise they mapped num methods to complexity in the java plugin, might be worth to take a look see we would need to implement something similar.

**Comment by racodond** [comment]
Fixed in https://github.com/iwarapter/sonar-puppet/pull/171
