### ISSUE TITLE
[Parsing error] To be investigated

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#17]
The following piece of code does not parse:

```
File['logrotate.conf'] {
  content => template('logrotate/spec.erb'),
}
```

The root cause to be investigated...

**Comment by iwarapter** [comment]
Reviewed the full syntax (See https://docs.puppetlabs.com/puppet/latest/reference/lang_resources_advanced.html)

The resource type, which can be one of:
- A lowercase word with no quotes, like file.
- A resource type data type, like File, Resource[File] or Resource['file']. It must have a type but not a title.

Currently not handling the second part.

**Comment by iwarapter** [comment]
Given `It must have a type but not a title.` this will be probably require re-writing the entire resource grammar.
