### ISSUE TITLE
Parse metadata.json files and provide checks

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#174]
See http://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#write-a-metadatajson-file
See https://github.com/puppet-community/metadata-json-lint

**Comment by racodond** [comment]
SonarQube JSON plugin created: https://github.com/racodond/sonar-json-plugin.

**Comment by racodond** [comment]
Don't know where they get: https://github.com/puppet-community/metadata-json-lint/blob/master/lib/metadata_json_lint.rb#L79

**Comment by racodond** [comment]
@iwarapter I added a few checks. I'm now happy with it. Could you please have another quick look at it? If it's ok with you, I'll release it. Do you want me to add you in the license?

**Comment by iwarapter** [comment]
@racodond i'll take another look, no need to add me to the license i haven't contributed anything to it :)

**Comment by racodond** [comment]
You tested it and provided some feedback. I'll add you when you start contributing. I'm sure you'll find some bugs and you'll want to add some features.
