### ISSUE TITLE
Why variables standing by themselves should be quoted in resource titles and only there?

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#175]
Follow discussion at https://groups.google.com/d/msg/puppet-users/acTxmBfOAeU/vDHgqyAMHAAJ

**Comment by racodond** [comment]
@iwarapter Any thoughts about the Google group discussion? Should I revert https://github.com/iwarapter/sonar-puppet/commit/0b93482ae9b0d3583b9bb1097ca08cf455c87d16?

**Comment by iwarapter** [comment]
@racodond i think it should enforce the quoting of resource titles as per the style guide.
