### ISSUE TITLE
Failure during OneIncludePerLineCheck

### ISSUE THREAD

**Issue by camara-tech** [iwarapter/sonar-puppet#265]
Sonar-Runner execution fails with "Unable to analyze file" if an `include` is made with parenthesis,

Example: 

```
include( "stdlib", "apache" ) 
```

Exception log indicates: 

```
Caused by: java.lang.NullPointerException
    at com.iadams.sonarqube.puppet.checks.OneIncludePerLineCheck.visitNode(OneIncludePerLineCheck.java:55)
```

For Documentation on Include:
https://docs.puppet.com/puppet/3.8/reference/function.html#include

Thanks for this plugin!

**Comment by iwarapter** [comment]
a vote for release has started which includes this fix: 

https://groups.google.com/forum/m/#!topic/sonarqube/R37SU66fL0s
