### ISSUE TITLE
Double-check slash comment pattern

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#29]
@iwarapter: I'm not sure to understand https://github.com/iwarapter/sonar-puppet/blob/master/puppet-squid/src/main/java/com/iadams/sonarqube/puppet/lexer/PuppetLexer.java#L54. What is `|#[^\\n\\r].*` for? Just a typo? I updated this regular expression in PR https://github.com/iwarapter/sonar-puppet/pull/30

**Comment by racodond** [comment]
@iwarapter: As you merge PR #30, you can close this issue if it's ok with you.

**Comment by iwarapter** [comment]
@racodond Not sure why that was there i'm assuming i probably had all single line comments as one type to begin with maybe?
