### ISSUE TITLE
Do not use parenthesis when calling a statement function

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#47]
Statement functions: https://docs.puppetlabs.com/puppet/latest/reference/lang_functions.html#list-of-built-in-statement-functions

**Comment by iwarapter** [comment]
@racodond do you have any more parser issues?

**Comment by racodond** [comment]
No remaining parsing error. I didn't run a SonarQube analysis on all our Puppet code yet though. But for sure you did a great work. It's time to start writing rules and fine tune the grammar when necessary. I'll try to find some time before the end of the week to write some rules and dive into the grammar.

**Comment by iwarapter** [comment]
No worries, let me know when you run it. I'm going to review the [style guide](http://docs.puppetlabs.com/guides/style_guide.html#the-puppet-language-style-guide) and see what i can add rules for.

**Comment by racodond** [comment]
Doesn't bring that much value. I'm closing it.
