### ISSUE TITLE
[Parsing error] $logstash::conffile[$name] not considered as an accessor

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#54]
The following piece of code cannot be parsed:

```
file { "${config_dir}/logstash.config":
  source  => $logstash::conffile[$name],
}
```

I guess that is because `$logstash::conffile[$name]` is not considered as an accessor. It should be considered as so like `$logstash::conffile[1]`

**Comment by iwarapter** [comment]
This can be fixed quite easily by adding the VARIABLE grammar to the grammar syntax, but should this not also support any EXPRESSION that can resolve to the numerical index?
