### ISSUE TITLE
puppet:ResourceDefaultUsed brings no value

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#69]
@iwarapter To be discussed but rule puppet:ResourceDefaultUsed doesn't bring any value for now. I'm not keen of having such rules even at INFO level.

**Comment by iwarapter** [comment]
So the reason for this was to help highlight instances of where they had been used as although using them isn't wrong, it can easily cause all sorts of issues if used poorly. If there is a better way we can easily expose the uses happy to look into it.

**Comment by racodond** [comment]
It's more a manual check than an automated check. I'd prefer to let users implement a very simple XPath check if they want to flag all usages of resource default statements to review them. What do you think?

**Comment by iwarapter** [comment]
Yeah i agree i think an XPath rule is a good fit here.

**Comment by racodond** [comment]
OK. I'll let you remove the related code then?
