### ISSUE TITLE
What other checks / features shall we add before the next release?

### ISSUE THREAD

**Issue by iwarapter** [iwarapter/sonar-puppet#74]
@racodond What do you think we need to add before the next release?

I was thinking we should look at the following style guide issues:

https://docs.puppetlabs.com/guides/style_guide.html#class-inheritance
https://docs.puppetlabs.com/guides/style_guide.html#symbolic-links
https://docs.puppetlabs.com/guides/style_guide.html#resource-names

What else do you think we need before its ready for a 0.2.0 release?

**Comment by racodond** [comment]
I'd like to get rid off Puppet Lint (that embeds the rules you mentioned above). We already have rewritten half of the rules. A few more days of work and we can kill Puppet Lint. OK with you? To not both work on the same rules, let's create an issue and assigned it while starting working on a Puppet Lint rule replacement.

**Comment by iwarapter** [comment]
I'd like to get rid of puppet lint too, but make sure we support (enough) of the important rules. Apart from the ones i listed which others do you think we should include?

**Comment by iwarapter** [comment]
Also once we reach this milestone i might start looking into how we can implement support for the future (4.x) parser, but this is still aspirational i had a quick chat on the google groups and believe i have a rough idea of how this could be achieved:
https://groups.google.com/forum/#!topic/sonarqube/9kQNWZw0Bs0

**Comment by iwarapter** [comment]
@racodond i have created issues for all of the checks i listed feel free to pick up the ones you want and add new issues for any others we want to replace. Add the remove puppet lint milestone so we can track our progress https://github.com/iwarapter/sonar-puppet/milestones
