### ISSUE TITLE
replace puppet lint rule ensure_not_symlink_target

### ISSUE THREAD

**Issue by iwarapter** [iwarapter/sonar-puppet#77]
https://docs.puppetlabs.com/guides/style_guide.html#symbolic-links
http://puppet-lint.com/checks/ensure_not_symlink_target/

**Comment by iwarapter** [comment]
@racodond I have implemented the check, however im not sure if its the best way, as it will detect any string usage, i was thinking of checking if the first character of the string started '/' as this will always be the start of any fully qualified file path. Thoughts?

**Comment by racodond** [comment]
@iwarapter To make it clearer, I'd make this rule a little bit more generic: "ensure property of file resource should be valid". Per https://docs.puppetlabs.com/references/latest/type.html#file-attribute-ensure, in the description of the rule, I'd say that valid values are: `present`, `absent` (also called `false`), `file`, `directory`, and `link`. Also state that the rule enforce:

> However, we recommend using link and target explicitly, since this behavior can be harder to read.

Then, you just have to check that the value of the `ensure` parameter is a string and in this case raise an issue whatever the value (just one corner case though, don't raise an issue if the string contains only a variable, see `CheckStringUtils`, there's already a function that checks it).

**Comment by iwarapter** [comment]
@racodond cheers for the feedback, just pulled in latest master changes got nasty conflict to fix then will publish the updates.

**Comment by iwarapter** [comment]
@racodond i think this covers the core changes, still need to update the description.

**Comment by racodond** [comment]
@iwarapter Your implementation does not cover Resource Default and Resource Override. See https://github.com/iwarapter/sonar-puppet/blob/feature/Add_rule_puppet_url_without_modules/puppet-checks/src/main/java/com/iadams/sonarqube/puppet/checks/PuppetURLModulesCheck.java#L58 for example.

**Comment by iwarapter** [comment]
@racodond cheers for the link, have added checks for resource default and resource override.
