### ISSUE TITLE
replace puppet lint rule inherits_across_namespaces

### ISSUE THREAD

**Issue by iwarapter** [iwarapter/sonar-puppet#79]
http://puppet-lint.com/checks/inherits_across_namespaces/
http://docs.puppetlabs.com/guides/style_guide.html#class-inheritance

**Comment by iwarapter** [comment]
@racodond would you mind taking a look at the new rule?

**Comment by racodond** [comment]
@iwarapter My review: https://github.com/iwarapter/sonar-puppet/commit/596102ad72c70ecbae2ab460262c63b00b6c08d7 and the PR: https://github.com/iwarapter/sonar-puppet/pull/105

**Comment by iwarapter** [comment]
@racodond cheers, i like to restructuring of the rule i keep thinking of starting at the top (classdef in this case) instead of the part that matters (class_parent).

**Comment by racodond** [comment]
Yep. And it's more efficient because you visit just a few nodes in this cases instead of all class nodes.
