### ISSUE TITLE
Replace all puppet lint rules dealing with quotes

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#83]
1. All variables must be enclosed in braces when interpolated in a string => https://github.com/iwarapter/sonar-puppet/pull/86
2. Single Quoted String Containing Variables => https://github.com/iwarapter/sonar-puppet/pull/84
3. All strings must be enclosed in single quotes, unless they contain variables or single quotes + Variables standing by themselves should not be quoted => https://github.com/iwarapter/sonar-puppet/pull/85
4. Variables standing by themselves should not be quoted, unless they are a resource title => https://github.com/iwarapter/sonar-puppet/pull/87
5. Double quotes should be used rather than escaping when a string contains single quotes => https://github.com/iwarapter/sonar-puppet/pull/123
6. unquoted_node_name => https://github.com/iwarapter/sonar-puppet/pull/90

**Comment by iwarapter** [comment]
@racodond regarding #90 where did you find it was deprecated as the language specs for both 3.8 and the future parser support this? I'll implement the rule in a branch and we decide we want it.

**Comment by racodond** [comment]
@iwarapter Per the language specification:
- 3.8: http://docs.puppetlabs.com/puppet/3.8/reference/lang_node_definitions.html#naming
- latest: http://docs.puppetlabs.com/puppet/4.2/reference/lang_node_definitions.html#naming

and per your implementation of the grammar that follows those specifications: https://github.com/iwarapter/sonar-puppet/blob/master/puppet-squid/src/main/java/com/iadams/sonarqube/puppet/api/PuppetGrammar.java#L365

unquoted node names are not valid.

Thus our parser would fail parsing:

```
node mynode {
  include common
  include apache, squid
}
```

That is the expected behavior. Thus implementing a rule that checks for unquoted node names is useless. Correct or am I missing something?

**Comment by iwarapter** [comment]
Unfortunately what the docs say and the specifics of what there grammar implement are not the same:
https://github.com/puppetlabs/puppet/blob/3.x/lib/puppet/parser/grammar.ra#L677

Thats the hostname definition which allows for unquoted names. My grammar is wrong, i shall correct this and add the rule.

**Comment by racodond** [comment]
> Unfortunately what the docs say and the specifics of what there grammar implement are not the same:
> https://github.com/puppetlabs/puppet/blob/3.x/lib/puppet/parser/grammar.ra#L677

Ah OK. I added this link to our PuppetGrammar file. See https://github.com/iwarapter/sonar-puppet/pull/122

> Thats the hostname definition which allows for unquoted names. My grammar is wrong, i shall correct this and add the rule.

Cool.

**Comment by racodond** [comment]
All done with guidelines about quotes with the last PR https://github.com/iwarapter/sonar-puppet/pull/123

**Comment by iwarapter** [comment]
#125 covers node names, once merged we can close :)
