### ISSUE TITLE
[Parsing error] Function call in parameter default value is not supported

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#9]
The following piece of code does not parse:

```
class ssh (
  $domain_name = hiera('abc'),
) {}
```

**Comment by iwarapter** [comment]
@racodond This should now work as expected, can you confirm?

**Comment by racodond** [comment]
I confirm. Thanks!
I added a specific unit test for PARAMETER: https://github.com/iwarapter/sonar-puppet/commit/c3da6c4c0cf7549586a3a110305c8d17c588f72a

**Comment by iwarapter** [comment]
:+1:
