### ISSUE TITLE
Replace Pplint:2sp_soft_tabs

### ISSUE THREAD

**Issue by racodond** [iwarapter/sonar-puppet#98]

**Comment by iwarapter** [comment]
@racodond i suspect this will require extensions to the lexer to support indentations, see: https://github.com/SonarCommunity/sonar-python/tree/master/python-squid/src/main/java/org/sonar/python/lexer

**Comment by racodond** [comment]
Nope. Python lexer needs to deal with indentation I guess because Python is based on indentation (there's no block token like braces).

**Comment by racodond** [comment]
But this rule won't be simple to implement...
